spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/geocoder
    username: geocoder
    password: geocoder
    driverClassName: org.postgresql.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl : true
    hibernate:
      ddl-auto: update
